# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Game.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'Game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import os
import sys
sys.path.append(os.path.dirname("Buffer"))


import Buffer.Player_pb2 as Player__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nGame.proto\x12\x0b\x64istributed\x1a\x0cPlayer.proto\"[\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bMAX_PLAYERS\x18\x03 \x01(\x05\x12$\n\x07players\x18\x04 \x03(\x0b\x32\x13.distributed.Player\"M\n\x07\x43ontext\x12\x0e\n\x06\x63hange\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x1f\n\x04game\x18\x03 \x01(\x0b\x32\x11.distributed.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAME']._serialized_start=41
  _globals['_GAME']._serialized_end=132
  _globals['_CONTEXT']._serialized_start=134
  _globals['_CONTEXT']._serialized_end=211
# @@protoc_insertion_point(module_scope)
