# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GameServer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'GameServer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import os
import sys
sys.path.append(os.path.dirname("Buffer"))
import Buffer.Resource_pb2 as Resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10GameServer.proto\x12\x0b\x64istributed\x1a\x0eResource.proto\"f\n\nGameServer\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x15\n\rresourceLimit\x18\x03 \x01(\x05\x12\'\n\x08resource\x18\x04 \x01(\x0b\x32\x15.distributed.Resource\"\x19\n\x06Health\x12\x0f\n\x07isAlive\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GameServer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESERVER']._serialized_start=49
  _globals['_GAMESERVER']._serialized_end=151
  _globals['_HEALTH']._serialized_start=153
  _globals['_HEALTH']._serialized_end=178
# @@protoc_insertion_point(module_scope)
