# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
import os
import sys
sys.path.append(os.path.dirname("Buffer"))

import Buffer.GameServer_pb2 as GameServer__pb2
import Buffer.Game_pb2 as Game__pb2
import Buffer.Player_pb2 as Player__pb2
import Buffer.Result_pb2 as Result__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in GameService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connectPlayer = channel.unary_unary(
                '/distributed.Server/connectPlayer',
                request_serializer=Player__pb2.Player.SerializeToString,
                response_deserializer=Result__pb2.Result.FromString,
                _registered_method=True)
        self.disconnectPlayer = channel.unary_unary(
                '/distributed.Server/disconnectPlayer',
                request_serializer=Player__pb2.Player.SerializeToString,
                response_deserializer=Result__pb2.Result.FromString,
                _registered_method=True)
        self.checkHealth = channel.unary_unary(
                '/distributed.Server/checkHealth',
                request_serializer=GameServer__pb2.Health.SerializeToString,
                response_deserializer=Result__pb2.Result.FromString,
                _registered_method=True)
        self.sendUpdate = channel.unary_unary(
                '/distributed.Server/sendUpdate',
                request_serializer=Game__pb2.Context.SerializeToString,
                response_deserializer=Result__pb2.Result.FromString,
                _registered_method=True)
        self.createGame = channel.unary_unary(
                '/distributed.Server/createGame',
                request_serializer=Game__pb2.Setting.SerializeToString,
                response_deserializer=Result__pb2.Result.FromString,
                _registered_method=True)




def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connectPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.connectPlayer,
                    request_deserializer=Player__pb2.Player.FromString,
                    response_serializer=Result__pb2.Result.SerializeToString,
            ),
            'disconnectPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.disconnectPlayer,
                    request_deserializer=Player__pb2.Player.FromString,
                    response_serializer=Result__pb2.Result.SerializeToString,
            ),
            'checkHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.checkHealth,
                    request_deserializer=GameServer__pb2.Health.FromString,
                    response_serializer=Result__pb2.Result.SerializeToString,
            ),
            'sendUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.sendUpdate,
                    request_deserializer=Game__pb2.Context.FromString,
                    response_serializer=Result__pb2.Result.SerializeToString,
            ),
            'createGame': grpc.unary_unary_rpc_method_handler(
                    servicer.createGame,
                    request_deserializer=Game__pb2.Setting.FromString,
                    response_serializer=Result__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.Server', rpc_method_handlers)

