# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MasterService.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'MasterService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import os
import sys
sys.path.append(os.path.dirname("Service"))


import Service.GameServer_pb2 as GameServer__pb2
import Service.Result_pb2 as Result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MasterService.proto\x1a\x10GameServer.proto\x1a\x0cResult.proto\"&\n\x03req\x12\x1f\n\ngameServer\x18\x01 \x01(\x0b\x32\x0b.GameServer\"\x1e\n\x03res\x12\x17\n\x06result\x18\x01 \x01(\x0b\x32\x07.Result2&\n\x06Master\x12\x1c\n\x0eregisterServer\x12\x04.req\x1a\x04.resb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MasterService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQ']._serialized_start=55
  _globals['_REQ']._serialized_end=93
  _globals['_RES']._serialized_start=95
  _globals['_RES']._serialized_end=125
  _globals['_MASTER']._serialized_start=127
  _globals['_MASTER']._serialized_end=165
# @@protoc_insertion_point(module_scope)
