# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings


import os
import sys
sys.path.append(os.path.dirname("Buffer"))

import Buffer.GameServer_pb2 as GameServer__pb2
import Buffer.Result_pb2 as Result__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MasterService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerServer = channel.unary_unary(
                '/distributed.Master/registerServer',
                request_serializer=GameServer__pb2.GameServer.SerializeToString,
                response_deserializer=Result__pb2.Result.FromString,
                _registered_method=True)
        self.requestServer = channel.unary_unary(
                '/distributed.Master/requestServer',
                request_serializer=Result__pb2.Register.SerializeToString,
                response_deserializer=Result__pb2.Response.FromString,
                _registered_method=True)

def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerServer': grpc.unary_unary_rpc_method_handler(
                    servicer.registerServer,
                    request_deserializer=GameServer__pb2.GameServer.FromString,
                    response_serializer=Result__pb2.Result.SerializeToString,
            ),
            'requestServer': grpc.unary_unary_rpc_method_handler(
                    servicer.requestServer,
                    request_deserializer=Result__pb2.Register.FromString,
                    response_serializer=Result__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.Master', rpc_method_handlers)

