# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Resource.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'Resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Game_pb2 as Game__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eResource.proto\x1a\nGame.proto\"9\n\x08Resource\x12\x14\n\x0cMAX_SESSIONS\x18\x01 \x01(\x05\x12\x17\n\x08sessions\x18\x02 \x03(\x0b\x32\x05.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCE']._serialized_start=30
  _globals['_RESOURCE']._serialized_end=87
# @@protoc_insertion_point(module_scope)

def create(MAX_SESSIONS, sessions):
    return Resource(MAX_SESSIONS=MAX_SESSIONS, sessions=sessions)